[package]
name = "klymene"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members = ["klymene_srv", "klymene_tty"]

[[bin]]
name = "klymene_srv"
path = "klymene_srv/src/main.rs"
test = true

[[bin]]
name = "klymene_tty"
path = "klymene_tty/src/main.rs"

[dependencies]
tokio = { version = "1.49.0", features = ["full"] }
