[package]
name = "klymene"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members = ["klymene-srv", "klymene-tty"]

[[bin]]
name = "klymene-srv"
path = "klymene-srv/src/main.rs"
test = true

[[bin]]
name = "klymene-tty"
path = "klymene-tty/src/main.rs"

[dependencies]
tokio = { version = "1.49.0", features = ["full"] }
